// Renders the package catalog from config.json (settings) and packages.json
// (auto-generated by scripts/build-catalog.mjs). Loaded with `defer`, so the
// DOM is ready by the time this runs.
(function () {
    "use strict";

    const emptyEl = document.getElementById("empty");

    function fetchJson(url) {
        return fetch(url, { cache: "no-cache" }).then((r) => {
            if (!r.ok) throw new Error(url + " -> HTTP " + r.status);
            return r.json();
        });
    }

    async function boot() {
        emptyEl.textContent = "Loading packages…";
        emptyEl.classList.remove("hidden");
        try {
            const [config, data] = await Promise.all([
                fetchJson("./config.json"),
                fetchJson("./packages.json"),
            ]);
            const packages = Array.isArray(data) ? data : (data && data.packages) || [];
            render(config || {}, packages);
        } catch (err) {
            console.error("Failed to load catalog:", err);
            emptyEl.textContent = "Could not load packages. Please try again later.";
            emptyEl.classList.remove("hidden");
        }
    }

    function render(CONFIG, PACKAGES) {
        // ---- static config ----
        document.getElementById("brand-name").textContent = CONFIG.handle;
        document.getElementById("title").textContent = CONFIG.title;
        document.getElementById("lede").textContent = CONFIG.lede;
        document.title = CONFIG.title;
        const prof = CONFIG.profileUrl;
        document.getElementById("profile-link").href = prof;
        document.getElementById("foot-link").href = prof;
        document.getElementById("foot-left").textContent =
            "© " + new Date().getFullYear() + " · @" + CONFIG.handle;

        const listEl = document.getElementById("list");
        const chipsEl = document.getElementById("chips");
        const countEl = document.getElementById("count");
        const input = document.getElementById("filter");

        // reset the empty-state text to its filter meaning (boot used it for loading)
        emptyEl.textContent = "Nothing matches that filter.";

        let activeCat = null; // null = All
        let query = "";

        const esc = (s) =>
            String(s).replace(/[&<>"']/g, (c) =>
                ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])
            );

        // A version counts as "pre-release" if its core is below 1.0.0
        // (i.e. major version is 0, like 0.9.1) OR it carries a
        // -alpha / -beta / -rc suffix (like 1.0.0-rc.2).
        function isPreRelease(version) {
            if (!version) return false;
            const v = String(version).trim().replace(/^v/i, "");
            const core = v.split("+")[0]; // drop build metadata
            if (core.includes("-")) return true; // has a pre-release tag
            const major = parseInt(core.split(".")[0], 10);
            return Number.isFinite(major) && major < 1;
        }

        // ---- icons ----
        const copyIcon =
            '<svg width="14" height="14" viewBox="0 0 24 24" fill="none"><rect x="9" y="9" width="11" height="11" rx="2" stroke="currentColor" stroke-width="1.6"/><path d="M5 15V5a2 2 0 0 1 2-2h10" stroke="currentColor" stroke-width="1.6"/></svg>';
        const okIcon =
            '<svg width="14" height="14" viewBox="0 0 24 24" fill="none"><path d="m5 13 4 4 10-11" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>';

        // ---- derive categories in first-appearance order ----
        const cats = [];
        PACKAGES.forEach((p) => {
            p._cat = p.category || "Other";
            if (!cats.includes(p._cat)) cats.push(p._cat);
        });
        const countOf = (c) => PACKAGES.filter((p) => p._cat === c).length;

        // ---- chips ----
        function makeChip(label, cat, n) {
            const b = document.createElement("button");
            b.type = "button";
            b.className = "chip";
            b.dataset.cat = cat == null ? "" : cat;
            b.innerHTML = esc(label) + ' <span class="n">' + n + "</span>";
            b.addEventListener("click", () => {
                activeCat = activeCat === cat ? null : cat; // click active chip to clear
                apply();
            });
            return b;
        }
        chipsEl.appendChild(makeChip("All", null, PACKAGES.length));
        cats.forEach((c) => chipsEl.appendChild(makeChip(c, c, countOf(c))));

        // ---- one card ----
        function card(p, i) {
            const el = document.createElement("article");
            el.className = "pkg reveal";
            el.style.animationDelay = i * 50 + "ms";
            el.dataset.search = (p.id + " " + (p.name || "") + " " + (p.desc || "") + " " + (p._cat || "") + (isPreRelease(p.version) ? " pre-release beta " + (CONFIG.betaLabel || "") : "")).toLowerCase();

            const links = [];
            if (p.repo) links.push(`<a href="${esc(p.repo)}" target="_blank" rel="noopener">Repo</a>`);
            if (p.docs) links.push(`<a href="${esc(p.docs)}" target="_blank" rel="noopener">Docs</a>`);
            if (p.changelog) links.push(`<a href="${esc(p.changelog)}" target="_blank" rel="noopener">Changelog</a>`);

            el.innerHTML = `
				<div class="pkg-head">
					<span class="pkg-id">${esc(p.id)}</span>
					<button class="cat-pill" type="button" data-cat="${esc(p._cat)}">${esc(p._cat)}</button>
					${p.version ? `<span class="ver">${esc(p.version)}</span>` : ""}
					${isPreRelease(p.version) ? `<span class="beta">${esc(CONFIG.betaLabel || "Pre-release")}</span>` : ""}
				</div>
				${p.name ? `<div class="pkg-name">${esc(p.name)}</div>` : ""}
				${p.desc ? `<p class="pkg-desc">${esc(p.desc)}</p>` : ""}
				<div class="copybar">
					<div class="url" tabindex="0">${esc(p.gitUrl)}</div>
					<button class="copy-btn" type="button" aria-label="Copy install URL">${copyIcon}<span>Copy</span></button>
				</div>
				${links.length ? `<div class="pkg-links">${links.join("")}</div>` : ""}
				${p.note ? `<p class="pkg-note">⚑ ${esc(p.note)}</p>` : ""}
			`;

            el.querySelector(".copy-btn").addEventListener("click", () => copy(p.gitUrl, el.querySelector(".copy-btn")));
            el.querySelector(".cat-pill").addEventListener("click", () => {
                activeCat = p._cat;
                apply();
                chipsEl.scrollIntoView({ behavior: "smooth", block: "nearest" });
            });
            return el;
        }

        // ---- copy with fallback ----
        function copy(text, btn) {
            const done = () => {
                btn.classList.add("done");
                btn.innerHTML = okIcon + "<span>Copied</span>";
                setTimeout(() => {
                    btn.classList.remove("done");
                    btn.innerHTML = copyIcon + "<span>Copy</span>";
                }, 1500);
            };
            if (navigator.clipboard && navigator.clipboard.writeText) {
                navigator.clipboard.writeText(text).then(done).catch(() => fallback(text, done));
            } else {
                fallback(text, done);
            }
        }
        function fallback(text, done) {
            const t = document.createElement("textarea");
            t.value = text;
            t.style.position = "fixed";
            t.style.opacity = "0";
            document.body.appendChild(t);
            t.select();
            try { document.execCommand("copy"); done(); } catch (e) { }
            document.body.removeChild(t);
        }

        // ---- build sections ----
        cats.forEach((c) => {
            const sec = document.createElement("section");
            sec.className = "section";
            sec.dataset.cat = c;
            sec.innerHTML =
                `<div class="section-head"><h2>${esc(c)}</h2><span class="n" data-secn></span></div><div class="cards"></div>`;
            const wrap = sec.querySelector(".cards");
            PACKAGES.filter((p) => p._cat === c).forEach((p, i) => wrap.appendChild(card(p, i)));
            listEl.appendChild(sec);
        });

        // ---- combined filter: category AND text ----
        function apply() {
            document.querySelectorAll(".chip").forEach((ch) =>
                ch.classList.toggle("active", ch.dataset.cat === (activeCat || ""))
            );

            let shown = 0;
            document.querySelectorAll(".section").forEach((sec) => {
                const catMatch = !activeCat || sec.dataset.cat === activeCat;
                let inSec = 0;
                sec.querySelectorAll(".pkg").forEach((n) => {
                    const textMatch = !query || n.dataset.search.includes(query);
                    const show = catMatch && textMatch;
                    n.classList.toggle("hidden", !show);
                    if (show) inSec++;
                });
                sec.classList.toggle("hidden", inSec === 0);
                const sn = sec.querySelector("[data-secn]");
                if (sn) sn.textContent = inSec;
                shown += inSec;
            });

            emptyEl.classList.toggle("hidden", shown !== 0);
            countEl.textContent =
                shown + " / " + PACKAGES.length + " package" + (PACKAGES.length === 1 ? "" : "s");
        }

        input.addEventListener("input", () => {
            query = input.value.trim().toLowerCase();
            apply();
        });

        apply();
        requestAnimationFrame(() =>
            document.querySelectorAll(".reveal").forEach((n) => n.classList.add("in"))
        );
    }

    boot();
})();
